algoritmo Classe
real num1, num2;

inicio
    // void
    escreva("digite o 1º valor)
    leia( num1);
    escreva("digite o 2º valor)
    leia( num2);
    Soma(num1,num2)
    Soma(num1,num2)
    Soma(num1,num2)
    Soma(num1,num2)


    // retorna real
    
    escreva(OutraSoma(num1,num2))
    
    escreva(OutraSoma(num1,num2))
fim

void Soma( real primeiroValor, real segundoValor){
   
    escreva( primeiroValor + segundoValor)

}
real OutraSoma(real primeiroValor, real segundoValor){
    return primeiroValor + segundoValor
}