algoritmo Medicamento
    real valorMedicamento1, valorMedicamento2;
    literal nomeMedicamento1, nomeMedicamento2;
    inicio
        escreva ("informe o nome do 1º medicamento:");
        leia(nomeMedicamento1);
        escreva("informe quanto custa" + nomeMedicamento1);
        leia(valorMedicamento1);
        escreva ("informe o nome do 2º medicamento:");
        leia(nomeMedicamento2);
        escreva("informe quanto custa" + nomeMedicamento2);
        leia(valorMedicamento2);
        escreva("O" + nomeMedicamento1 + "custa R$:" + valorMedicamento1);
        escreva("O" + nomeMedicamento2 + "custa R$:" + valorMedicamento2);
    fim